### PR TITLE
Add anchor parameter to DisplayText

### PR DESCRIPTION
**Pull request by hchargois**
The anchor parameter is required to easily (and correctly) place text on the drawn image.

See https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html

### CODE REVIEW

**Comment by mathoudebine** [comment]
Hi @hchargois
Thanks for the PR! Can you rebase/update your branch with the latest commits on `main`? I have added a new Github CI check to quickly identify visual impacts on themes rendering.
Just want to check possible impacts of your changes on existing themes

**Comment by hchargois** [comment]
Rebase is done :)

**Comment by mathoudebine** [comment]
The new CI actions have run and it seems your changes impact System Monitor existing themes, as some text fields have shifted.
Here is an example about a theme named "bash-dark-green":

Original rendering / new rendering with your changes:
screenshot-bash-dark-green screenshot-bash-dark-green

Diff between the two rendering:
diff-bash-dark-green

Because of all the existing themes on this repository but also from the community, I cannot merge your changes as-is to avoid breaking current themes support.

Is it possible to update your changes so that the text fields are still displayed in their original positions by default?

**Comment by hchargois** [comment]
Is it possible to run these tests locally?

**Comment by hchargois** [comment]
So, what was done manually before this PR, i.e. computing the empty "margins" around the drawn text via a call to `textbbox` at the `(0,0)` position, and subtracting them to the drawn text's location, is actually just the same as simply using the `"lt"` (left-top) anchor.

So I just added that anchor to the drawing functions for the themes. I was able to run the github action locally and confirm that all screencaps are now exactly the same as before.

IMO, I think the library's `DisplayText` should still default to "la" (left-ascender). When drawing text, you usually don't want it to jump up and down depending on whether you're displaying a `_`, a `x` or a `X`, which have different heights. You want the baseline to stay at the same position, so you use "la" or alternatively "ls" (left-baseline). The fact that Pillow's default is "la" gives even more weight to this.

However, this does mean that people who are using `DisplayText` directly in their own projects will have their text moved down a bit. We could also add the "lt" anchor as default of `DisplayText` to avoid breaking these users. I'll let you decide if you want a small breaking change now to get a better default, or no breaking change but keep lugging around an imperfect default.

**Comment by mathoudebine** [comment]
Thanks for the changes, I agree it is best to have the anchor default to `la` for `DisplayText`. Unfortunately it is too late to apply this change for the System Monitor themes, but I will add a disclaimer for people using the function in their own code that the behavior has changed.

**Pull request merged**
