### PR TITLE
Update bash green theme with radial

### PR DESCRIPTION
**Pull request by Rollbacke**
**Don't merge !**

I maybe made a mistake on my first PR, so I'm doing it again with this one.
I finally understanding how radials work.

I've a last problem with de radial: the percentage in the middle of the radial flicker at each refresh (maybe it's because it's layered?)

Do you have an idea ?

### CODE REVIEW

**Comment by Rollbacke** [comment]
Re,
When a percentage is with a single digit (or "100"), without the unit (%), it is right-aligned. It would be better to be able to specify that.

**Comment by mathoudebine** [comment]
Thanks for the theme updates! For the centered text it is currently not implemented, because it has to be done manually by guessing the max. text size first, which is sometimes impossible for non monospaced-fonts.

The flickering as you guessed is because of the content layering. To avoid it you can use the "text" features of the radial progress bar:
```yaml
  GPU:
    INTERVAL: 1
    PERCENTAGE:
      RADIAL:
        SHOW: True
        X: 366
        Y: 155
        RADIUS: 35
        WIDTH: 7
        MIN_VALUE: 0
        MAX_VALUE: 100
        ANGLE_START: 120
        ANGLE_END: 60
        ANGLE_STEPS: 20
        ANGLE_SEP: 0
        CLOCKWISE: True
        BAR_COLOR: 255, 0, 173
        SHOW_TEXT: True
        SHOW_UNIT: True
        FONT: generale-mono/GeneraleMonoA.ttf
        FONT_SIZE: 16
        FONT_COLOR: 128, 255, 255
        BACKGROUND_IMAGE: background.png
```
Radial progress bars offer the ability to display text inside the radius. The properties are the same as text sensors: `SHOW_TEXT / SHOW_UNIT / FONT / FONT_SIZE / FONT_COLOR`. This way the text is updated with the radial progress bars and there will be no flickering.

Can you create new themes with your modifications instead of editing existing ones? Something like `bask-dark-green-radial` / `bash-dark-green-gpu-radial` this way people can choose whether they want radial or not!

**Comment by Rollbacke** [comment]
Hi Mathoudebine,
I finally have some time to fix this.
I'll take care of it, I'll give you a new PR after that.

**Comment by mathoudebine** [comment]
Thanks, looking forward to it!

**Pull request closed without merging**
